# Compile stage
FROM golang:1.14 AS build-env

# Build Delve
RUN go get github.com/go-delve/delve/cmd/dlv

ADD . /dockerdev
WORKDIR /dockerdev

RUN go build -gcflags="all=-N -l" -o /server

# Final stage
FROM debian:buster

EXPOSE 5000 5000

WORKDIR /
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /server /
COPY ./data-sample ./data-sample

CMD ["/dlv", "--listen=:5000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]