# Start from the golang base image version 1.14
FROM golang:1.14

WORKDIR /go/src/app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o main .

# Expose port 4200 to the outside world
EXPOSE 4200

# Command to run the executable
CMD ["./main"]